Added a Better Single Parameterized Command Group and Improved Motor Saftey
Spartronics4915/2017-STEAMworks pull request #59
Opened 2017-02-19 22:24 UTC by pietroglyph

* There is now a DriveCommandGroup that can take any number of parameters variadically for each of our autonomous atoms
* There is a new StopCommand for the end of the command group so that motor safety is kept happy in autonomous
* The IMU is now clear when it is having trouble, and will tell you when it is unplugged or just not initalized so you *dont* have to spend 45 minutes debugging it and it just turns out that the wire fell out
* The wheel circumference constant is different to account for a discrepency in calculating revolutions from inches, but this doesn't completly fix the problem
* Renamed TurnDegreesIMU to TurnDegreesIMUCommand to fit the de facto convention that we seem to have
_IMU turning is still broken! This pull request is just to get the most significant changes into upstream_

2017-02-19 22:50 UTC, phroa requested changes
If it works, fine, but I'd like to suggest something like accepting an `Action...` rather than trying to parse strings for anything you make in the future.

These Actions just have to be tiny objects with a type and a value; so you could pass `(Action.turn(90), Action.drive(5), Action.turn(135))` as the arguments rather than `"Turn", "90", "Drive", "5", "Turn", "135")

2017-02-19 22:50 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/commands/DriveStraightCommand.java
> +    private static final double k_P = 1.7, k_D = 0, k_I = 0, k_F = 0; // P was 1.7
But it still is 1.7?

2017-02-19 22:50 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/OI.java
> +                "Drive", "120")); // This is the length from the diamond plate with the robot length and an inch (just to be safe) subtracted
I don't think your comments here (and in the commands above) match up with the numbers.

Also, inline math like that is impenetrable.  Maybe add some local variables above the `.put`s where you explain the movements a little more?

2017-02-19 22:50 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/commands/DriveStraightCommand.java
> +        m_pidController.setAbsoluteTolerance(0.053); // This is the tolerance for error for reaching our target, targeting one inch
`1 / (3 * (2 * Math.PI))` is a little longer but slightly easier to read 'one inch over the circumference of a 3 inch radius wheel'

2017-02-19 22:50 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/subsystems/Drivetrain.java
> +    private static final double WHEEL_CIRCUMFERENCE = 20.06; //WHEEL_DIAMETER * Math.PI;
Why change this?

2017-02-19 22:50 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/commands/groups/DriveCommandGroup.java
> +            double value = Double.parseDouble(params[i + 1]);
This'll crash the robot if `params` is an odd number in length and `[i + 1]` goes past the last entry in `params`.

2017-02-19 22:51 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/commands/DriveStraightCommand.java
> +        m_pidController.setAbsoluteTolerance(0.053); // This is the tolerance for error for reaching our target, targeting one inch
This goes for most of the magic numbers in the project

2017-02-19 23:17 UTC, pietroglyph commented on src/org/usfirst/frc/team4915/steamworks/commands/DriveStraightCommand.java
> +    private static final double k_P = 1.7, k_D = 0, k_I = 0, k_F = 0; // P was 1.7
This is in case I make any changes in the future, it's so I don't have to go back to the diff.

2017-02-20 02:28 UTC, phroa commented on src/org/usfirst/frc/team4915/steamworks/subsystems/Drivetrain.java
> +
...k

2017-02-20 02:28 UTC, phroa approved these changes

2017-02-20 02:29 UTC, merged